export const sessionChannels = {
  unusedRunData: 'sessions:unused-run-data',
  removeUnusedRunData: 'sessions:remove-unused-run-data',
  remove: 'sessions:remove',
  pendingRemovals: 'sessions:pending-removals',
  history: 'sessions:history',
  exportHistory: 'sessions:export-history',
  impact: 'sessions:impact',
  configuration: 'sessions:configuration',
  command: 'sessions:command',
  get: 'sessions:get',
  list: 'sessions:list',
  events: 'sessions:events',
  subscribe: 'sessions:subscribe',
  unsubscribe: 'sessions:unsubscribe',
  delivery: 'sessions:delivery',
} as const
